# General  
no_eval: False
finetune: False
partial_train: null

# Traning 
epochs: 40
checkpoint_frequency: 30
batch_size: 64
dropout: 0.0
learning_rate: 0.00
weight_decay: 0.01
lr_decay: 0.99
pretrain_3d_curriculum: 30

# Model
maxlen: 81
dim_feat: 512
mlp_ratio: 2
depth: 2
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
data_root: data/motion3d/MB3D_f81s9/
subset_list: [3dgait, pdgait]
label_list: ['1', '2']
subset_ratio: 1
clip_len: 81
data_stride: 9
rootrel: True
sample_stride: 2
num_joints: 17
gt_2d: False
joints_index: joint

# Loss
loss_type: joint
parts_len: [5,3,3,3,3]
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_trajectory_interpart: 1
lambda_trajectory_intrapart: 0.5
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0

# Augmentation
synthetic: True   # synthetic: don't use 2D detection results, fake it (from 3D)
flip: True
mask_ratio: 0.05
mask_T_ratio: 0.1
noise: True
noise_parameters: 
  mean: 0
  std: 0.002
d2c_params_path: params/d2c_params.pkl
